#!/usr/bin/env php
<?php

/*
 * This file is part of the Sprites package.
 *
 * (c) Pierre Minnieur <pierre@falsep.com>
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with this source code.
 */

use Symfony\Component\Console\Application;

use Falsep\Sprites\Command\GenerateDynamicSpritesCommand,
    Falsep\Sprites\Command\GenerateFixedSpritesCommand;

require __DIR__.'/autoload.php';

$console = new Application('Sprites', file_get_contents(__DIR__.'/VERSION'));
$console->add(new GenerateDynamicSpritesCommand());
$console->add(new GenerateFixedSpritesCommand());
$console->run();
